# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: https://github.com/ghqls2003 # the base hostname & protocol for your site, e.g. http://example.com
baseurl: /Blog # the subpath of your site, e.g. /blog
title: Ryong Blog
description: "Never Ending Effort, Self-Confidence"
keywords: 'jekyll,theme,blog'
author:
  name: by Ryong
  job_title:
  location:
  email:
  github: https://github.com/ghqls2003
 
paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
